# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vivado/EE415/projectTest4myVGA/projectTest4myVGA.srcs/sources_1/bd/design_1/ip/design_1_axi_myVGA_0_0/design_1_axi_myVGA_0_0.xci
# IP: The module: 'design_1_axi_myVGA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/Vivado/EE415/projectTest4myVGA/projectTest4myVGA.gen/sources_1/bd/design_1/ip/design_1_axi_myVGA_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: C:/Xilinx/Vivado/EE415/projectTest4myVGA/projectTest4myVGA.srcs/sources_1/bd/design_1/ip/design_1_axi_myVGA_0_0/design_1_axi_myVGA_0_0.xci
# IP: The module: 'design_1_axi_myVGA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/Vivado/EE415/projectTest4myVGA/projectTest4myVGA.gen/sources_1/bd/design_1/ip/design_1_axi_myVGA_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet
