# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "design_1_smartconnect_1_0_synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/NoahG/Downloads/ttte2/ttte/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.xci
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/bd_88fd_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/bd_88fd_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/bd_88fd_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/bd_88fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/bd_88fd_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/bd_88fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/bd_88fd_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/bd_88fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/bd_88fd_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_19/bd_88fd_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/bd_88fd_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/bd_88fd_sarn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/bd_88fd_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/bd_88fd_srn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_25/bd_88fd_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_26/bd_88fd_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_26/bd_88fd_sarn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_27/bd_88fd_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_27/bd_88fd_srn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/bd_88fd_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/bd_88fd_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/bd_88fd_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/bd_88fd_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/bd_88fd_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/bd_88fd_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_31/bd_88fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/bd_88fd_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/bd_88fd_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/bd_88fd_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/bd_88fd_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/bd_88fd_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/bd_88fd_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/bd_88fd_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/bd_88fd_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/bd_88fd_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/bd_88fd_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_38/bd_88fd_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/bd_88fd_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/bd_88fd_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_40/bd_88fd_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_40/bd_88fd_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_41/bd_88fd_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_41/bd_88fd_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_42/bd_88fd_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_42/bd_88fd_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_43/bd_88fd_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_43/bd_88fd_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_45/bd_88fd_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_46/bd_88fd_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_46/bd_88fd_m02arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_47/bd_88fd_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_47/bd_88fd_m02rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_48/bd_88fd_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_48/bd_88fd_m02awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_49/bd_88fd_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_49/bd_88fd_m02wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_50/bd_88fd_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_50/bd_88fd_m02bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_52/bd_88fd_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_53/bd_88fd_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_53/bd_88fd_m03arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_54/bd_88fd_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_54/bd_88fd_m03rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_55/bd_88fd_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_55/bd_88fd_m03awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_56/bd_88fd_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_56/bd_88fd_m03wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_57/bd_88fd_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_57/bd_88fd_m03bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_59/bd_88fd_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_60/bd_88fd_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_60/bd_88fd_m04arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_61/bd_88fd_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_61/bd_88fd_m04rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_62/bd_88fd_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_62/bd_88fd_m04awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_63/bd_88fd_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_63/bd_88fd_m04wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_64/bd_88fd_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_64/bd_88fd_m04bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_66/bd_88fd_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_67/bd_88fd_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_67/bd_88fd_m05arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_68/bd_88fd_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_68/bd_88fd_m05rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_69/bd_88fd_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_69/bd_88fd_m05awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_70/bd_88fd_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_70/bd_88fd_m05wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_71/bd_88fd_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_71/bd_88fd_m05bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_73/bd_88fd_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_74/bd_88fd_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_74/bd_88fd_m06arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_75/bd_88fd_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_75/bd_88fd_m06rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_76/bd_88fd_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_76/bd_88fd_m06awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_77/bd_88fd_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_77/bd_88fd_m06wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_78/bd_88fd_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_78/bd_88fd_m06bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_80/bd_88fd_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_81/bd_88fd_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_81/bd_88fd_m07arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_82/bd_88fd_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_82/bd_88fd_m07rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_83/bd_88fd_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_83/bd_88fd_m07awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_84/bd_88fd_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_84/bd_88fd_m07wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_85/bd_88fd_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_85/bd_88fd_m07bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_87/bd_88fd_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_88/bd_88fd_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_88/bd_88fd_m08arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_89/bd_88fd_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_89/bd_88fd_m08rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_90/bd_88fd_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_90/bd_88fd_m08awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_91/bd_88fd_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_91/bd_88fd_m08wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_92/bd_88fd_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_92/bd_88fd_m08bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_94/bd_88fd_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_95/bd_88fd_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_95/bd_88fd_m09arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_96/bd_88fd_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_96/bd_88fd_m09rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_97/bd_88fd_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_97/bd_88fd_m09awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_98/bd_88fd_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_98/bd_88fd_m09wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_99/bd_88fd_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_99/bd_88fd_m09bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_101/bd_88fd_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_102/bd_88fd_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_102/bd_88fd_m10arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_103/bd_88fd_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_103/bd_88fd_m10rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_104/bd_88fd_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_104/bd_88fd_m10awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_105/bd_88fd_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_105/bd_88fd_m10wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_106/bd_88fd_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_106/bd_88fd_m10bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_108/bd_88fd_m11s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_109/bd_88fd_m11arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_109/bd_88fd_m11arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_110/bd_88fd_m11rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_110/bd_88fd_m11rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_111/bd_88fd_m11awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_111/bd_88fd_m11awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_112/bd_88fd_m11wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_112/bd_88fd_m11wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_113/bd_88fd_m11bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_113/bd_88fd_m11bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/smartconnect.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1 -new_name design_1_smartconnect_1_0 -ip [get_ips design_1_smartconnect_1_0]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_smartconnect_1_0 -part xc7s50csga324-1 -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix design_1_smartconnect_1_0_ design_1_smartconnect_1_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_1_0_stub.v
 lappend ipCachedFiles design_1_smartconnect_1_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_1_0_stub.vhdl
 lappend ipCachedFiles design_1_smartconnect_1_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_1_0_sim_netlist.v
 lappend ipCachedFiles design_1_smartconnect_1_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_1_0_sim_netlist.vhdl
 lappend ipCachedFiles design_1_smartconnect_1_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp design_1_smartconnect_1_0.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips design_1_smartconnect_1_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all design_1_smartconnect_1_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_smartconnect_1_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_1_smartconnect_1_0_utilization_synth.rpt -pb design_1_smartconnect_1_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0.dcp c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0.dcp c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0_stub.v c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0_stub.vhdl c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0_sim_netlist.v c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/design_1_smartconnect_1_0_synth_1/design_1_smartconnect_1_0_sim_netlist.vhdl c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.ip_user_files/ip/design_1_smartconnect_1_0]} {
  catch { 
    file copy -force c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.v C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.ip_user_files/ip/design_1_smartconnect_1_0
  }
}

if {[file isdir C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.ip_user_files/ip/design_1_smartconnect_1_0]} {
  catch { 
    file copy -force c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0_stub.vhdl C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.ip_user_files/ip/design_1_smartconnect_1_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "design_1_smartconnect_1_0_synth_1" END { }
