# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.srcs/sources_1/bd/design_1/ip/design_1_displayModule_0_1/design_1_displayModule_0_1.xci
# IP: The module: 'design_1_displayModule_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.gen/sources_1/bd/design_1/ip/design_1_displayModule_0_1/design_1_displayModule_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_displayModule_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.srcs/sources_1/bd/design_1/ip/design_1_displayModule_0_1/design_1_displayModule_0_1.xci
# IP: The module: 'design_1_displayModule_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Xilinx/Vivado/EE415/projectTest20_vga2/projectTest20_vga2.gen/sources_1/bd/design_1/ip/design_1_displayModule_0_1/design_1_displayModule_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_displayModule_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
