# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/NoahG/Downloads/ttte2/ttte/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_0/design_1_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_0/design_1_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_0/design_1_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_axi_intc_0/design_1_microblaze_riscv_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_axi_intc_0/design_1_microblaze_riscv_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_axi_intc_0/design_1_microblaze_riscv_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_mdm_2_0/design_1_mdm_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_mdm_2_0/design_1_mdm_2_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/bd_88fd_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/bd_88fd_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/bd_88fd_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/bd_88fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/bd_88fd_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/bd_88fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/bd_88fd_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/bd_88fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/bd_88fd_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_19/bd_88fd_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/bd_88fd_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/bd_88fd_sarn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/bd_88fd_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/bd_88fd_srn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_25/bd_88fd_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_26/bd_88fd_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_26/bd_88fd_sarn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_27/bd_88fd_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_27/bd_88fd_srn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/bd_88fd_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/bd_88fd_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/bd_88fd_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/bd_88fd_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/bd_88fd_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/bd_88fd_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_31/bd_88fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/bd_88fd_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/bd_88fd_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/bd_88fd_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/bd_88fd_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/bd_88fd_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/bd_88fd_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/bd_88fd_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/bd_88fd_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/bd_88fd_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/bd_88fd_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_38/bd_88fd_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/bd_88fd_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/bd_88fd_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_40/bd_88fd_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_40/bd_88fd_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_41/bd_88fd_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_41/bd_88fd_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_42/bd_88fd_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_42/bd_88fd_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_43/bd_88fd_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_43/bd_88fd_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_45/bd_88fd_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_46/bd_88fd_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_46/bd_88fd_m02arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_47/bd_88fd_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_47/bd_88fd_m02rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_48/bd_88fd_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_48/bd_88fd_m02awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_49/bd_88fd_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_49/bd_88fd_m02wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_50/bd_88fd_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_50/bd_88fd_m02bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_52/bd_88fd_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_53/bd_88fd_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_53/bd_88fd_m03arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_54/bd_88fd_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_54/bd_88fd_m03rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_55/bd_88fd_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_55/bd_88fd_m03awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_56/bd_88fd_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_56/bd_88fd_m03wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_57/bd_88fd_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_57/bd_88fd_m03bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_59/bd_88fd_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_60/bd_88fd_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_60/bd_88fd_m04arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_61/bd_88fd_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_61/bd_88fd_m04rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_62/bd_88fd_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_62/bd_88fd_m04awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_63/bd_88fd_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_63/bd_88fd_m04wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_64/bd_88fd_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_64/bd_88fd_m04bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_66/bd_88fd_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_67/bd_88fd_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_67/bd_88fd_m05arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_68/bd_88fd_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_68/bd_88fd_m05rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_69/bd_88fd_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_69/bd_88fd_m05awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_70/bd_88fd_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_70/bd_88fd_m05wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_71/bd_88fd_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_71/bd_88fd_m05bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_73/bd_88fd_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_74/bd_88fd_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_74/bd_88fd_m06arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_75/bd_88fd_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_75/bd_88fd_m06rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_76/bd_88fd_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_76/bd_88fd_m06awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_77/bd_88fd_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_77/bd_88fd_m06wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_78/bd_88fd_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_78/bd_88fd_m06bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_80/bd_88fd_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_81/bd_88fd_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_81/bd_88fd_m07arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_82/bd_88fd_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_82/bd_88fd_m07rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_83/bd_88fd_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_83/bd_88fd_m07awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_84/bd_88fd_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_84/bd_88fd_m07wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_85/bd_88fd_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_85/bd_88fd_m07bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_87/bd_88fd_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_88/bd_88fd_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_88/bd_88fd_m08arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_89/bd_88fd_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_89/bd_88fd_m08rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_90/bd_88fd_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_90/bd_88fd_m08awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_91/bd_88fd_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_91/bd_88fd_m08wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_92/bd_88fd_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_92/bd_88fd_m08bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_94/bd_88fd_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_95/bd_88fd_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_95/bd_88fd_m09arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_96/bd_88fd_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_96/bd_88fd_m09rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_97/bd_88fd_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_97/bd_88fd_m09awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_98/bd_88fd_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_98/bd_88fd_m09wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_99/bd_88fd_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_99/bd_88fd_m09bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_101/bd_88fd_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_102/bd_88fd_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_102/bd_88fd_m10arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_103/bd_88fd_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_103/bd_88fd_m10rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_104/bd_88fd_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_104/bd_88fd_m10awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_105/bd_88fd_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_105/bd_88fd_m10wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_106/bd_88fd_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_106/bd_88fd_m10bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_108/bd_88fd_m11s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_109/bd_88fd_m11arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_109/bd_88fd_m11arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_110/bd_88fd_m11rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_110/bd_88fd_m11rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_111/bd_88fd_m11awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_111/bd_88fd_m11awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_112/bd_88fd_m11wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_112/bd_88fd_m11wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_113/bd_88fd_m11bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_113/bd_88fd_m11bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.gen/sources_1/bd/design_1/ip/design_1_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.srcs/constrs_1/imports/Downloads/Urbana.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.srcs/constrs_1/imports/Downloads/Urbana.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Xilinx/Vivado/EE415/projectTest23Combined/projectTest23Combined.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
