#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 6

/* Definitions for peripheral AXIANODE */
#define XPAR_AXIANODE_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXIANODE_BASEADDR 0x40020000
#define XPAR_AXIANODE_HIGHADDR 0x4002ffff
#define XPAR_AXIANODE_INTERRUPT_PRESENT 0x0
#define XPAR_AXIANODE_IS_DUAL 0x1
#define XPAR_AXIANODE_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXIANODE */
#define XPAR_XGPIO_0_BASEADDR 0x40020000
#define XPAR_XGPIO_0_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x1

/* Definitions for peripheral AXIBTN */
#define XPAR_AXIBTN_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXIBTN_BASEADDR 0x40050000
#define XPAR_AXIBTN_HIGHADDR 0x4005ffff
#define XPAR_AXIBTN_INTERRUPT_PRESENT 0x0
#define XPAR_AXIBTN_IS_DUAL 0x0
#define XPAR_AXIBTN_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXIBTN */
#define XPAR_XGPIO_1_BASEADDR 0x40050000
#define XPAR_XGPIO_1_HIGHADDR 0x4005ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x4
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral AXICATHODE */
#define XPAR_AXICATHODE_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXICATHODE_BASEADDR 0x40030000
#define XPAR_AXICATHODE_HIGHADDR 0x4003ffff
#define XPAR_AXICATHODE_INTERRUPT_PRESENT 0x0
#define XPAR_AXICATHODE_IS_DUAL 0x1
#define XPAR_AXICATHODE_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXICATHODE */
#define XPAR_XGPIO_2_BASEADDR 0x40030000
#define XPAR_XGPIO_2_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x8
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x1

/* Definitions for peripheral AXILED */
#define XPAR_AXILED_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXILED_BASEADDR 0x40000000
#define XPAR_AXILED_HIGHADDR 0x4000ffff
#define XPAR_AXILED_INTERRUPT_PRESENT 0x0
#define XPAR_AXILED_IS_DUAL 0x0
#define XPAR_AXILED_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXILED */
#define XPAR_XGPIO_3_BASEADDR 0x40000000
#define XPAR_XGPIO_3_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x10
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral AXIRGB */
#define XPAR_AXIRGB_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXIRGB_BASEADDR 0x40040000
#define XPAR_AXIRGB_HIGHADDR 0x4004ffff
#define XPAR_AXIRGB_INTERRUPT_PRESENT 0x0
#define XPAR_AXIRGB_IS_DUAL 0x1
#define XPAR_AXIRGB_GPIO_WIDTH 0x3

/* Canonical definitions for peripheral AXIRGB */
#define XPAR_XGPIO_4_BASEADDR 0x40040000
#define XPAR_XGPIO_4_HIGHADDR 0x4004ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x3
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_4_IS_DUAL 0x1

/* Definitions for peripheral AXISW */
#define XPAR_AXISW_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXISW_BASEADDR 0x40010000
#define XPAR_AXISW_HIGHADDR 0x4001ffff
#define XPAR_AXISW_INTERRUPT_PRESENT 0x0
#define XPAR_AXISW_IS_DUAL 0x0
#define XPAR_AXISW_GPIO_WIDTH 0xe

/* Canonical definitions for peripheral AXISW */
#define XPAR_XGPIO_5_BASEADDR 0x40010000
#define XPAR_XGPIO_5_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0xe
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_5_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x3
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x3
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x0
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 0
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 0
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x0
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral AXI_CUSTOM */
#define XPAR_AXI_CUSTOM_BASEADDR 0x44a00000
#define XPAR_AXI_CUSTOM_HIGHADDR 0x44a00fff

/* Canonical definitions for peripheral AXI_CUSTOM */
#define XPAR_AXI_VGA_0_BASEADDR 0x44a00000
#define XPAR_AXI_VGA_0_HIGHADDR 0x44a00fff

#define XPAR_MIG_0_BASEADDRESS 0x0
#define XPAR_MIG_0_HIGHADDRESS 0x7ffffff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 83333333
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 1
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 0
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7s50"

#endif  /* end of protection macro */