# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Urbana.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_riscv_0_0/design_1_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_riscv_0_axi_intc_0/design_1_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_2_0/design_1_mdm_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_2_0 || ORIG_REF_NAME==design_1_mdm_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_riscv_0_xlconcat_0/design_1_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_1_0 || ORIG_REF_NAME==design_1_smartconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vga_0_1/design_1_axi_vga_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vga_0_1 || ORIG_REF_NAME==design_1_axi_vga_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hdmi_tx_0_0/design_1_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hdmi_tx_0_0 || ORIG_REF_NAME==design_1_hdmi_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_VGA_0_0/design_1_VGA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_VGA_0_0 || ORIG_REF_NAME==design_1_VGA_0_0} -quiet] -quiet

# XDC: c:/Xilinx/Vivado/EE415/projectTest19vga/projectTest19vga.gen/sources_1/bd/design_1/design_1_ooc.xdc
